daixieadmin/models/order.py
# -*- coding: utf-8 -*-

from datetime import datetime

from daixieadmin.models import enum

from flask.ext.login import UserMixin

from daixieadmin import db

class Order(db.Model, UserMixin):

    __tablename__ = 'order'

    STATUS = enum(CREATED=0, PAID=1, SOLVEING=2, FINISHED=3)

    id = db.Column('id', db.Integer, primary_key=True)
    user_id = db.Column('user_id', db.Integer)
    cs_id = db.Column('cs_id', db.Integer)
    solver_id = db.Column('solver_id', db.Integer,default=0)
    status = db.Column('status', db.Integer, default = 0)
    create_time = db.Column('create_time', db.DateTime)
    require_time = db.Column('require_time', db.DateTime)
    expect_time = db.Column('expect_time', db.DateTime)
    title = db.Column('title', db.String)
    description = db.Column('description', db.String)
    supp_info = db.Column('supp_info', db.String)
    log = db.Column('log', db.String)
    grade = db.Column('grade', db.Integer)
    expect_hour = db.Column('expect_hour', db.FLOAT, default=0)
    actual_hour = db.Column('actual_hour', db.FLOAT, default=0)
    extra_item = db.Column('extra_item', db.String)
    extra_money = db.Column('extra_money', db.String)
    expect_order_price = db.Column('expect_order_price', db.FLOAT, nullable=False, default=0)
    actual_order_price = db.Column('actual_order_price', db.FLOAT, nullable=False, default=0)


    
    def __init__(self, user_id, cs_id, solver_id, require_time, expect_time, title, expect_hour, \
             expect_order_price, grade, actual_order_price=0, description=None, \
             extra_item=None, extra_money=None, log=''):
        self.user_id = user_id
        self.cs_id = cs_id
        self.solver_id = solver_id
        self.status = Order.STATUS.CREATED
        self.create_time = datetime.now()
        self.require_time = require_time
        self.expect_time = expect_time
        self.title = title
        self.description = description
        self.log = log
        self.grade = grade
        self.expect_hour = expect_hour
        self.actual_hour = None
        self.extra_item = extra_item
        self.extra_money = extra_money
        self.expect_order_price = expect_order_price
        self.actual_order_price = actual_order_price

    @property
    def user_email(self):
        from daixieadmin.biz.user import UserBiz
        user = UserBiz.get_user_by_id(self.user_id)
        return user.email

    @property
    def cs_email(self):
        from daixieadmin.biz.admin import AdminBiz
        cs = AdminBiz.get_admin_by_id(self.cs_id)
        return cs.email

    @property
    def solver_email(self):
        from daixieadmin.biz.admin import AdminBiz
        solver = AdminBiz.get_admin_by_id(self.solver_id)
        print "solver_email",solver.email
        return solver.email

    def __repr__(self):
        return '<Order %r %r %r %r>' % (self.id, self.user_id, self.cs_id, self.solver_id)

daixieadmin/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, url_for, redirect, render_template, request,send_from_directory,make_response

from flask_wtf import Form

from werkzeug.utils import secure_filename

from wtforms import TextField, FloatField, SelectField, DateTimeField, TextAreaField, DateTimeField,IntegerField
from wtforms.validators import DataRequired,  Length, Regexp, Email, NumberRange, Optional
from flask_wtf.file import FileField, FileAllowed, FileRequired

from flask.ext.login import login_required, current_user

from daixieadmin.biz.order import OrderBiz
from daixieadmin.biz.user import UserBiz
from daixieadmin.biz.admin import AdminBiz

from daixieadmin.utils.error import DaixieError, fail, success
from daixieadmin.utils.tools import save_file_with_order_id
from daixieadmin.utils.form import User_Exist
from daixieadmin.models.admin import Admin
from daixieadmin.models.order import Order
from daixieadmin import app
from daixieadmin.views import j_login_required

mod = Blueprint('order', __name__)

@mod.route('/create_order', methods=['GET', 'POST'])
@login_required
def create_order():
    '''
    创建订单
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    form = OrderForm()
    if not form.validate_on_submit():
        return render_template('order/create.html', form=form, nav_order_manage='active')

    
    file = request.files['supp_info'] 
    if file :   
        if not allowed_file(file.filename):
            fail("file type error")
            return render_template('order/create.html', form=form, nav_order_manage='active')

    user = UserBiz.get_user_by_email(form.user_email.data)

    cs = AdminBiz.get_admin_by_email(form.cs_email.data)
    solverid = 0
    if form.solver_email.data:
        solver = AdminBiz.get_solver_by_email(form.solver_email.data)
        solverid = solver.id


    order = Order(user.id, cs.id, solverid, form.require_time.data, form.expect_time.data, 
        form.title.data, form.expect_hour.data, form.expect_order_price.data, form.grade.data, 0, \
        form.description.data, form.extra_item.data, form.extra_money.data, form.log.data)

    
    try:
        ret = OrderBiz.create_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')   

    if file :
        order_id = order.id
        save_file_with_order_id(order_id, file)
        order.supp_info = secure_filename(file.filename)
    
    try:
        OrderBiz.edit_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')

    success(ret)
    return redirect(url_for('.my_list'))

@mod.route('/download/<int:id>', methods=['POST', 'GET'])
@j_login_required
def download_file(id):
    order = OrderBiz.get_order_by_id(id).first()
    filename = order.supp_info
    path = app.config['DIR_RESOURCES'] +'/'+ str(id) +'/'
    print "file to be downloaded is at : ", path
    return send_from_directory(path, filename, as_attachment=True)

def allowed_file(filename):
    return True
    #return '.' in filename and \
     #      filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@mod.route('/my_list')
@login_required
def my_list(page=1):
    '''
    查看我的所有订单
    '''
    
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS or current_user.type == Admin.ADMIN_TYPE.ADMIN:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page=1)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page=1)
    return render_template('order/list.html',searchform = searchform, my_list =pager, type=1, nav_order_manage='active')

@mod.route('/search_order',methods=['POST'])
@login_required
def search_order():
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    searchform = SearchForm()
    print "order : ",searchform.order_id.data, "solver :", searchform.solver_id.data
    result = OrderBiz.search_order_by_pager(1,searchform.order_id.data,searchform.solver_id.data,searchform.require_time.data)
    return render_template('order/list.html', searchform = searchform, order_list=result, type=type, nav_order_manage='active')

@mod.route('/order_list')
@login_required
def order_list(page=1):
    '''
    查看所有订单
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()

    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/list.html', searchform = searchform, order_list=pager, type=0, nav_order_manage='active')

@mod.route('/due_order')
@mod.route('/due_order/<int:page>')
@login_required
def due_order(page=0):
    '''
    
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    if page == 0:
        pager = None
        pager = OrderBiz.get_due_order_by_pager(1)
        return render_template('order/list.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')
    else :
        pager = None
        pager = OrderBiz.get_due_order_by_pager(page)
        return render_template('order/morelist.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')

@mod.route('/order_list/<int:page>')
@login_required
def order_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/morelist.html', order_list=pager, paginate=True, nav_order_manage='active')

@mod.route('/my_list/<int:page>')
@login_required
def my_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page)
    return render_template('order/morelist.html', my_list =pager, paginate=True, nav_order_manage='active', tpye=1)    


@mod.route('/more_info/<int:id>')
@login_required
def more_info(id):
    if not current_user.is_authenticated():
        fail(u'权限不足')
        return redirect(url_for('general.index'))
  
    order = OrderBiz.get_order_by_id(id).first()
    if current_user.type == Admin.ADMIN_TYPE.CS:
		return render_template('order/more_info_for_cs.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        return render_template('order/more_info_for_admin.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        return render_template('order/more_info_for_solver.html', order=order, nav_order_manage='active')

@mod.route('/edit_order/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if(current_user.type == Admin.ADMIN_TYPE.SOLVER):
        fail(u'用户权限不足')
        return redirect(url_for('general.index'))    
    if(current_user.type == Admin.ADMIN_TYPE.CS):
        return redirect(url_for('.edit_order_for_cs', id=id))
    else:
        return redirect(url_for('.edit_order_for_admin', id=id))


@mod.route('/edit_order_for_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_cs(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if current_user.type != Admin.ADMIN_TYPE.CS:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = CSEditOrderForm(obj=order)
    form.log.data = ''
    if not form.validate_on_submit():
        print "show order editing"
        return render_template('order/edit_order_for_cs.html', form=form, id=   id, order=order, nav_order_manage='active')
    
    file = request.files['supp_info']    
    if order.status>='1' and order.status <= form.status.data:
        order.status = form.status.data
    order.expect_time = form.expect_time.data
    order.title = form.title.data
    order.description = form.description.data
    order.log = order.log+form.log.data
    order.grade = form.grade.data
    order.expect_hour = form.expect_hour.data
    order.actual_hour = form.actual_hour.data

    if order.status == '3' and form.actual_order_price.data != 0 and form.actual_order_price is not None:
        order.actual_order_price = form.actual_order_price.data

    if file:
        save_file_with_order_id(id, file)
        print file.name
        order.supp_info = secure_filename(file.filename)

    #修改订单
    try:
        ret = OrderBiz.edit_order(order)
        success(ret)
    except DaixieError as e:
        fail(e)
        return render_template('order/edit_order_for_cs.html', form=form, id=id, order=order, nav_order_manage='active')

    return redirect(url_for('admin.home'))

@mod.route('/edit_order_for_admin/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_admin(id):
    if not current_user.is_authenticated() :
        return redirect(url_for('general.index'))    
    if current_user.type != Admin.ADMIN_TYPE.ADMIN:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = AdminEditOrderForm(obj=order)
    if not form.validate_on_submit():
        return render_template('order/edit_order_for_admin.html', form=form, id=id, order=order, nav_order_manage='active')
    

daixieadmin/views/user.py
# -*- coding: utf-8 -*-

from flask import Blueprint, url_for, redirect, render_template, request, abort

from flask_wtf import Form
from wtforms import TextField, PasswordField, SelectField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Regexp
from flask_wtf.file import FileField, FileAllowed, FileRequired

from flask.ext.sqlalchemy import Pagination
from flask.ext.login import login_required, current_user

from daixieadmin.biz.user import UserBiz
from daixieadmin.biz.admin import AdminBiz
from daixieadmin.models.user import User
from daixieadmin.models.admin import Admin
from daixieadmin.utils.error import DaixieError, fail, success, j_ok, j_err
from daixieadmin.utils.http import get_arg

mod = Blueprint('user', __name__)

@mod.route('/home')
@login_required
def home():
	'''
	主页
	'''
	return render_template('user/home.html')

@mod.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
	'''
	个人信息
	'''
	form = ProfileForm(obj=current_user)
	if not form.validate_on_submit():
		return render_template('user/setting.html', form=form)
	user = current_user
	form.populate_obj(user)
	#修改个人信息
	try:
		ret = UserBiz.edit_user_profile(user)
		success(ret)
	except DaixieError as e:
		fail(e)
	return redirect(url_for('.profile'))

@mod.route('/users', methods=['GET'])
@login_required
def j_search_user():
	email = request.args.get('email', '')
	query = request.args.get('query', '')
	page = get_arg('page', 1)
	type = request.args.get('type', '')
	#print "query is ",query

	if(type == 'user'):
		type = User.USER_TYPE.USER

	try:
		if email:
			user = UserBiz.get_user_by_email(email, type)
			users_pager = Pagination(None, 1, 1, 1, [user])
		else:
			users_pager = UserBiz.get_by_like(query, type, page, per_page=10)
	except DaixieError as e:
		return j_err(e)

	users = [{
	'id': user.email,
	'text': user.email,
	'account': user.account
	} for user in users_pager.items if user]

	return j_ok(u'搜索成功', items=users, pages=users_pager.pages)

@mod.route('/solvers', methods=['GET'])
@login_required
def j_search_solvers():
	email = request.args.get('email', '')
	query = request.args.get('query', '')
	page = get_arg('page', 1)
	type = request.args.get('type', '')

	type = Admin.ADMIN_TYPE.SOLVER

	try:
		if email:
			user = AdminBiz.get_cs_by_email(email, type)
			users_pager = Pagination(None, 1, 1, 1, [user])
		else:
			users_pager = AdminBiz.get_by_like(query, type, page, per_page=10)
	except DaixieError as e:
		return j_err(e)

	users = [{
	'id': user.email,
	'text': user.email
	} for user in users_pager.items if user]

	return j_ok(u'搜索成功', items=users, pages=users_pager.pages)
class ProfileForm(Form):
	sex_choices = [('0', u'男'), ('1', u'女')]
	email = TextField(u'登录邮箱', validators=[DataRequired(), Email()])
	nickname = TextField(u'昵称',[Regexp('[\s|\S]')])
	sex = SelectField(u'性别', choices=sex_choices, default='0')
	description = TextAreaField(u'自我介绍',[Regexp('[\s|\S]')])

daixieadmin/templates/order/create.html
{% extends 'layout.html' %}
{% from 'import/tools.html' import flashed_msg, errors,captcha %}
{% from 'import/tools.html' import error %}

{% block content %}

<h1>创建新订单</h1>
<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <form class="form-horizontal" id="profile-form" method="post" action="{{ url_for('order.create_order') }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.user_email.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    <input 
                    value="{{ form.user_email.data or '' }}" 
                    data-ajax-url="{{ url_for('user.j_search_user') }}" 
                    name="user_email" 
                    user_type="user" 
                    type="hidden" 
                    class="select" 
                    placeholder="请选择用户邮箱" 
                    required="required">
                    {{ error(form.errors['user_email']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.cs_email.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    <input 
                    value="{{ form.cs_email.data or '' }}" 
                    data-ajax-url="{{ url_for('admin.j_search_cs') }}" 
                    name="cs_email" 
                    type="hidden" 
                    class="select" 
                    placeholder="请选择客服邮箱" >
                    {{ error(form.errors['cs_email']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.solver_email.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    <input 
                    value="{{ form.solver_email.data or '' }}" 
                    data-ajax-url="{{ url_for('user.j_search_solvers') }}" 
                    name="solver_email" 
                    user_type="solver" 
                    type="hidden" 
                    class="select" 
                    placeholder="请选择解题员邮箱" 
                    required="required">
                    {{ error(form.errors['solver_email']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.require_time.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.require_time(class='form-control form_datetime') }}
                    {{ error(form.errors['require_time']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.expect_time.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.expect_time(class='form-control form_datetime') }}
                    {{ error(form.errors['expect_time']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.title.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.title(class='form-control') }}
                    {{ error(form.errors['title']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.expect_hour.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.expect_hour(class='form-control') }}
                    {{ error(form.errors['expect_hour']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.grade.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.grade(class='form-control') }}
                    {{ error(form.errors['grade']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.expect_order_price.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.expect_order_price(class='form-control') }}
                    {{ error(form.errors['expect_order_price']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.description.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.description(class='form-control') }}
                    {{ error(form.errors['description']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.supp_info.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.supp_info }}
                     {{ error(form.errors['supp_info']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.extra_item.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.extra_item(class='form-control') }}
                    {{ error(form.errors['extra_item']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.log.label(class="col-md-3 control-label") }}
                <div class="col-md-5">
                    {{ form.log(class='form-control', style="height:150px;resize:none;") }}
                    {{ error(form.errors['log']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5 col-md-offset-3">
                    <input class="btn btn-orange" type="submit" value="提交"/>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

{% block js %}
<script>
    create_order.run();
</script>
{% endblock js %}

daixieadmin/templates/order/edit_order_for_admin.html
{% extends 'layout.html' %}

{% from 'import/tools.html' import flashed_msg, errors %}
{% from 'import/tools.html' import error %}

{% block content %}

<h1>修改订单信息</h1>

<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <form class="form-horizontal" id="profile-form" method="post" action="{{ url_for('order.edit_order_for_admin', id=id) }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}

            <div class="form-group">
                <div class="col-md-2 control-label">用户邮箱</div>
                <div class="col-md-5">
                    <div class="form-control">{{order.user_email}}</div>
                </div>
            </div>
            <div class="form-group">
                {{ form.cs_email.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.cs_email(class='form-control') }}
                    {{ error(form.errors['cs_email']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.solver_email.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    <input 
                    value="{{ form.solver_email.data }}" 
                    data-ajax-url="{{ url_for('user.j_search_solvers') }}" 
                    name="solver_email" 
                    user_type="solver" 
                    type="hidden" 
                    class="select" 
                    data-placeholder="{{order.solver_email}}">
                    {{ error(form.errors['solver_email']) }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2 control-label">创建时间</div>
                <div class="col-md-5">
                    <div class="form-control">{{order.create_time}}</div>
                </div>
            </div>
            <div class="form-group">
                {{ form.status.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.status(class='form-control') }}
                    {{ error(form.errors['status']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.require_time.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.require_time(class='form-control form_datetime') }}
                    {{ error(form.errors['require_time']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.expect_time.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.expect_time(class='form-control form_datetime') }}
                    {{ error(form.errors['expect_time']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.title.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.title(class='form-control') }}
                    {{ error(form.errors['title']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.description.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.description(class='form-control') }}
                    {{ error(form.errors['description']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.supp_info.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.supp_info() }}
                    {% if order.supp_info%}
                        已上传文件:{{order.supp_info}}
                    {% endif %}
                    {{ error(form.errors['supp_info']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.log.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.log(class='form-control', style="height:150px;resize:none;") }}
                    {{ error(form.errors['log']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.grade.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.grade(class='form-control') }}
                    {{ error(form.errors['grade']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.expect_hour.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.expect_hour(class='form-control') }}
                    {{ error(form.errors['expect_hour']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.actual_hour.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.actual_hour(class='form-control') }}
                    {{ error(form.errors['actual_hour']) }}
                </div>
            </div>
            <div class="form-group">
                {{ form.extra_item.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.extra_item(class='form-control') }}
                    {{ error(form.errors['extra_item']) }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2 control-label">预计订单价格</div>
                <div class="col-md-5">
                    <div class="form-control">{{order.expect_order_price}}</div>
                </div>
            </div>
            {% if order.actual_order_price %}
            <div class="form-group">
                <div class="col-md-2 control-label">实际订单价格</div>
                <div class="col-md-5">
                    <div class="form-control">{{order.actual_order_price}}</div>
                </div>
            </div>
            {% else %}
            <div class="form-group">
                {{ form.actual_order_price.label(class="col-md-2 control-label") }}
                <div class="col-md-5">
                    {{ form.actual_order_price(class='form-control') }}
                    {{ error(form.errors['actual_order_price']) }}
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <div class="col-md-5 col-md-offset-2">
                    <input class="btn btn-orange" type="submit" value="提交"/>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
{% block js %}
<script>
    create_order.run();
</script>
{% endblock js %}

daixieadmin/templates/order/list.html
{% extends 'layout.html' %}

{% from 'import/tools.html' import list, error %}

{% if searchform%}
{% block search %}
  <form id="searchform" class="form-horizontal" action="{{url_for('order.search_order')}}", method="POST">
      <div class="form-group">
        {{ searchform.order_id.label(class="col-md-2 control-label") }}
      <div class="col-md-3">
        {{ searchform.order_id(class='form-control') }}
        {{ error(searchform.errors['order_id']) }}
      </div>
        {{ searchform.solver_id.label(class="col-md-2 control-label") }}
      <div class="col-md-3">
        {{ searchform.solver_id(class='form-control') }}
        {{ error(searchform.errors['solver_id']) }}
      </div>
      </div>
      <div class="form-group">
        {{ searchform.require_time.label(class="col-md-2 control-label") }}
      <div class="col-md-3">
        {{ searchform.require_time(class='form-control form_datetime') }}
        {{ error(searchform.errors['require_time']) }}
      </div>
        <input value="Search" class="col-md-1 btn btn-large col-md-offset-1" type="submit"></input>
        <div class="col-md-1 col-md-offset-1"> <a class=" btn btn-primary btn-large "href="{{url_for('order.due_order')}}">查询即将到期订单</a></div>
      </div>
  </form> 
{% endblock %}

{% endif %}

{% block content %}

{% if order_list %}
{{list(order_list, type)}}
{% endif %}
{% if my_list %}
{{list(my_list, type)}}
{% endif %}

{% endblock %}

{% block js%}
<SCRIPT TYPE="text/javascript">
        $("#o-next").click(function(event){
        event.preventDefault();
        
        var url = $("#onextpage").attr('href'); 
        
        $.get(url,function(data,status){
            $("#main").html(data);
        });

      });

      $("#o-pre").click(function(event){
        event.preventDefault();
        
        var url = $("#oprepage").attr('href'); 
        
        $.get(url,function(data,status){
            $("#main").html(data);
        });

      });
</SCRIPT>
{% endblock %}