daixieadmin/views/admin.py
# -*- coding: utf-8 -*-


from flask import Blueprint,  url_for, redirect, render_template, request
from flask_wtf import Form
from wtforms import TextField, PasswordField, SelectField
from wtforms.validators import Email, Regexp, DataRequired, EqualTo
                            
from flask.ext.login import login_required, current_user
from flask.ext.sqlalchemy import Pagination

from daixieadmin.utils.error import DaixieError, fail, success, j_ok, j_err
from daixieadmin.utils.http import get_arg

from daixieadmin.models.admin import Admin
from daixieadmin.models.user import User

from daixieadmin.biz.admin import AdminBiz
from daixieadmin.biz.user import UserBiz


mod = Blueprint('admin', __name__)

@mod.route('/home')
@login_required
def home():
	'''
	主页
	'''
	return render_template('admin/home.html', nav_home='active')

@mod.route('/cs_list', methods=['GET', 'POST'])
@login_required
def cs_list():
    '''
    
    '''
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        all_cs = AdminBiz.get_all_CS();
        all_user = UserBiz.get_all_user();
        return render_template('admin/cs_list.html', cs_list=all_cs, user_list=all_user, nav_user_manage='active')
    else:
        return redirect(url_for('general.index'))

@mod.route('/add_cs', methods=['GET', 'POST'])
@login_required
def add_cs():
    '''
    创建解题员和客服
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        form = RegisterForm()
        if not form.validate_on_submit():
            print form.errors
            return render_template('admin/add_cs.html', form=form, nav_user_manage='active')
        try:
            if form.user_type.data=='0':
                cs = Admin(form.email.data, form.passwd.data, form.qq.data)
                ret = AdminBiz.add_CS(cs)
            else:
                solver = Admin(form.email.data, form.passwd.data, form.qq.data)
                ret = AdminBiz.add_solver(solver)
            success(ret)
        except DaixieError as e:
            fail(e)
            return render_template('admin/add_cs.html', form=form, nav_user_manage='active')
        return render_template('admin/add_cs.html', form=form, nav_user_manage='active')     
    else:
        return redirect(url_for('general.index'))

@mod.route('/update_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def update_cs(id):
    '''
    update cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    cs=AdminBiz.get_admin_by_id(id);
    form = AccountForm();
    if not form.validate_on_submit():
        return render_template('admin/update.html', form=form, id=id, type="CS", nav_user_manage='active')
    try:
        cs.passwd = form.passwd.data
        ret = AdminBiz.cs_commit_update(cs=cs)
    except DaixieError as e:
        fail(e)
        return redirect(url_for('.cs_list'))     
    success(ret)
    return redirect(url_for('.cs_list')) 

@mod.route('/update_solver/<int:id>', methods=['GET', 'POST'])
@login_required
def update_solver(id):
    '''
    update solver
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    solver=UserBiz.get_user_by_id(id);
    form = AccountForm();
    if not form.validate_on_submit():
        return render_template('admin/update.html', form=form, id=id, type="SOLVER", nav_user_manage='active')
    try:
        solver.passwd = form.passwd.data
        ret = UserBiz.solver_commit_update(solver=solver)
    except DaixieError as e:
        fail(e)
        return redirect(url_for('.cs_list'))     
    success(ret)
    return redirect(url_for('.cs_list')) 

@mod.route('/delete_cs', methods=['GET', 'POST'])
@mod.route('/delete_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_cs(id):
    '''
    delete cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    cs = AdminBiz.get_admin_by_id(id)
    try:
        ret = AdminBiz.delete_CS(cs=cs)
    except DaixieError as e:
        fail(e) 
    success(ret)
    return redirect(url_for('.cs_list'))

@mod.route('/delete_solver', methods=['GET', 'POST'])
@mod.route('/delete_solver/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_solver(id):
    '''
    delete cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    solver = UserBiz.get_user_by_id(id)
    try:
        ret = UserBiz.delete_solver(solver)
        success(ret)
    except DaixieError as e:
        fail(e) 
    
    return redirect(url_for('.cs_list'))

@mod.route('/cs', methods=['GET'])
@login_required
def j_search_cs():
    email = request.args.get('email', '')
    query = request.args.get('query', '')
    page = get_arg('page', 1)

    try:
        if email:
            cs = AdminBiz.get_cs_by_email(email)
            cs_pager = Pagination(None, 1, 1, 1, [cs])
        else:
            cs_pager = AdminBiz.get_by_like(query, 0,page, per_page=10)
    except DaixieError as e:
        return j_err(e)

    cs = [{
    'id': cs.email,
    'text': cs.email
    } for cs in cs_pager.items if cs]

    return j_ok(u'搜索成功', items=cs, pages=cs_pager.pages)

class RegisterForm(Form):
    user_type_choices = [('0', u'客服'), ('1', u'解题员')]

    user_type=SelectField(u'用户类型', choices=user_type_choices, default='0')
    email = TextField(u'邮箱地址*', validators=[DataRequired(), Email(message=u'请填写正确的邮箱地址')])
    passwd = PasswordField(u'密码*', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    passwd_confirm = PasswordField(u'确认密码*', validators=[DataRequired(), EqualTo('passwd', message=u'密码不一致')])
    qq = TextField(u'QQ号*', validators=[DataRequired()])

class AccountForm(Form):
    passwd = PasswordField(u'新密码*', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    passwd_confirm = PasswordField(u'确认密码*', validators=[DataRequired(), EqualTo('passwd', message=u'密码不一致')])

daixieadmin/views/general.py
# -*- coding: utf-8 -*-


from flask import Blueprint, url_for, redirect, render_template
from flask_wtf import Form
from wtforms import TextField, PasswordField, BooleanField, SelectField
from wtforms.validators import Email, Regexp, DataRequired, EqualTo
                            
from flask.ext.login import login_required, current_user

from daixieadmin.utils.error import DaixieError, fail, success

from daixieadmin.models.admin import Admin

from daixieadmin.biz.admin import AdminBiz

#from functools import wraps

mod = Blueprint('general', __name__)

# def admin_required(func):

#     @wraps(func)
#     def wrapper(*args, **kwargs):
#         if not current_user.get_id()==1:
#             fail("not qualified!")
#         return func(*args, **kwargs)
#     return wrapper

@mod.route('/', methods=['GET', 'POST'])
def index():
    '''
    网站首页
    '''
    if current_user.is_authenticated():
        return render_template('admin/home.html', nav_home='active')
    return redirect(url_for('.login'))

@mod.route('/login', methods=['GET','POST'])
def login():
    '''
    登录
    '''
    form = LoginForm()
    if not form.validate_on_submit():
        return render_template('general/login.html', form=form, nav_login='active')
    email = form.email.data
    passwd = form.passwd.data
    auto = form.auto.data

    admin = Admin(email, passwd)
    try:
        ret = AdminBiz.admin_login(admin, auto)
    except DaixieError as e:
        fail(e)
        return render_template('general/login.html', form=form, nav_login='active')
    success(ret)
    return redirect(url_for('.index'))

@mod.route('/logout', methods=['GET','POST'])
@login_required
def logout():
    '''
    注销
    '''
    try:
        AdminBiz.admin_logout()
    except DaixieError as e:
        fail(e)
    return redirect(url_for('.index'))

@mod.route('/daixie_rule')
@login_required
def daixie_rule():
    return render_template("general/daixie_rule.html")

class LoginForm(Form):
    email = TextField(u'邮箱', validators=[DataRequired(), Email(message=u'请填写正确的邮箱地址')])
    passwd = PasswordField(u'密码', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    auto = BooleanField(u'自动登录', default=False)

class RegisterForm(Form):
    user_type_choices = [('0', u'客服'), ('1', u'解题员')]
    user_type=SelectField(u'性别', choices=user_type_choices, default='0')
    email = TextField(u'邮箱地址*', validators=[DataRequired(), Email(message=u'请填写正确的邮箱地址')])
    passwd = PasswordField(u'密码*', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    passwd_confirm = PasswordField(u'确认密码*', validators=[DataRequired(), EqualTo('passwd', message=u'密码不一致')])

daixieadmin/templates/general/activate_ok.html
{% extends 'layout.html' %}
{% from 'import/tools.html' import flashed_msg %}

{% block title %}
注册
{% endblock title %}

{% block content %}

{{ flashed_msg() }}
<div class="mail">
    <p><a href="{{ url }}">若浏览器没有跳转，点击此处进入主页</a></p>
</div>

{% endblock content %}

daixieadmin/templates/general/cs_list.html
{% extends 'layout.html' %}
{% from 'import/tools.html' import flashed_msg, errors,captcha %}
{% from 'import/tools.html' import error %}

{% block content %}

<table id="order_list_table" class="table table-striped table-bordered">
  <tr>
      <th>TYPE</th>
      <th>ID</th>
      <th>EMAIL</th>
  </tr>
  {%for cs in cs_list%}
  <tr>
      <td>customer_supporter</td>
      <td>{{cs.id}}</td>
      <td>{{cs.email}}</td>
      <td>          
           <a class="btn btn-warning" href="{{url_for('admin.delete_cs', id=cs.id)}}">
            delete</a>
      </td>
      <td>
          <a class="btn btn-info" href="">修改</a>
      </td>
  </tr>
  {% endfor %}

{%for solver in solver_list%}
  <tr>
      <td>solver</td>
      <td>{{solver.id}}</td>
      <td>{{solver.email}}</td>
      <td>    
           <a class="btn btn-warning" href="{{url_for('admin.delete_solver', id=solver.id)}}">
            delete</a>
      </td>
      <td>
          <a class="btn btn-info" href="">修改</a>
      </td>
  </tr>
{% endfor %}

  </table>

  <div class="col-md-8 col-md-offset-2">
    <div class="row">
        <form class="form-horizontal col-md-offset-2" method="post" action="{{ url_for('admin.management') }}">
          {{ form.hidden_tag() }}
          {{ form.csrf_token }}
            <div class="form-group">
                  <label class="col-md-3 control-label">类型</label>
                <div class="col-md-5">
                    {{ form.user_type(class='form-control',  placeholder='type',required='required') }}
                    {{ error(form.errors['user_type']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">邮箱</label>
                <div class="col-md-5">
                    {{ form.email(class='form-control', type='email', placeholder='邮箱', required='required') }}
                    {{ error(form.errors['email']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">密码</label>
                <div class="col-md-5">
                    {{ form.passwd(class='form-control', placeholder="密码") }}
                    {{ error(form.errors['passwd']) }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">确认密码</label>
                <div class="col-md-5">
                    {{ form.passwd_confirm(class='form-control', placeholder="确认密码") }}
                    {{ error(form.errors['passwd_confirm']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-5">
                    <input class="btn btn-orange" type="submit" value="&nbsp;&nbsp;添加&nbsp;&nbsp;">
                </div>
            </div>

        </form>
    </div>
</div>

{% endblock content %}

daixieadmin/templates/general/daixie_rule.html
{% extends 'layout.html' %}

{% block content %}
{% from 'import/heji_rule.html' import heji_rule %}
<div  class="well">
<h3 class="alert alert-info">请认真阅读以下协议，要使用我们的服务，必须同意此协议。</h3>
	{{ heji_rule() }}
	<table>
		<tr>
	     <td><a class="btn btn-info" href="{{ url_for('user.user_info') }}" style="width:100px">同意</a></td>
	     <td><a class="btn btn-info" href="{{ url_for('general.logout') }}" style="width:100px">不同意</a></td>
	    </tr>
	</table>
</div>

{% endblock%}

daixieadmin/templates/general/index.html
{% extends 'layout.html' %}

{% block content %}
<div>
    <div class="headline text-center">
        <h1>{{ config['SITE_NAME'] }}</h1>
        <small>大学生代写作业平台.</small>
    </div>
    <br>
    <div class="center-block well share" style="width:660px;">
        <div class="row">
            <p class="lead text-center">目前已有 <span class="strong">100</span> 个大学生需要代写作业</p>
            <p class="lead text-center">加入我们, 获得更多优惠 :)</p>
        </div>
    </div>

</div>
{% endblock content %}

{% block js %}
<script>
    $("#scroll").Scroll({line:1,speed:300,timer:1000}); 
</script>
{% endblock js %}

daixieadmin/templates/general/login.html
{% extends 'layout.html' %}
{% from 'import/tools.html' import flashed_msg, errors %}

{% block title %}
登录 - {{ config['SITE_NAME'] }}
{% endblock title %}

{% block content %}

<div class="row">
    
    <div class="page-header">
        <h2>登录{{ config['SITE_NAME'] }}</h2>
    </div>

    <form class="form-horizontal" id="register-form" method="post" action="{{ url_for('general.login') }}">    
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="col-md-2 control-label") }}
            <div class="col-md-5">
                {{ form.email(class='form-control', type='email', placeholder="请输入邮箱", required='required') }}
            </div>
        </div>

        <div class="form-group">
            {{ form.passwd.label(class="col-md-2 control-label") }}
            <div class="col-md-5">
                {{ form.passwd(class='form-control', placeholder="请输入密码") }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5 col-md-offset-2">
                <div class="checkbox">
                    <label>{{ form.auto() }}下次自动登录</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-5 col-md-offset-2">
                <input class="btn btn-orange" type="submit" value="登录"/>
            </div>
        </div>
    </form>

</div>

{% endblock content %}

daixieadmin/templates/general/register.html
{% extends 'layout.html' %}
{% from 'import/tools.html' import flashed_msg, errors,captcha %}
{% from 'import/tools.html' import error %}

{% block content %}

<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <h2 class="headline text-center">加入{{ config['SITE_NAME'] }}, 和全北京的小伙伴一起合寄</h2>
        <form class="form-horizontal col-md-offset-2" method="post" action="{{ url_for('general.register') }}">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <div class="form-group">
                <label class="col-md-3 control-label">邮箱</label>
                <div class="col-md-5">
                    {{ form.email(class='form-control', type='email', placeholder='邮箱', required='required') }}
                    {{ error(form.errors['email']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">密码</label>
                <div class="col-md-5">
                    {{ form.passwd(class='form-control', placeholder="密码") }}
                    {{ error(form.errors['passwd']) }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">确认密码</label>
                <div class="col-md-5">
                    {{ form.passwd_confirm(class='form-control', placeholder="确认密码") }}
                    {{ error(form.errors['passwd_confirm']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">验证码</label>
                <div class="col-md-5">
                    {{ form.captcha(id="input-captcha", class="form-control", required='required', placeholder='输入验证码') }}
                    <img class="captcha input-small" src="{{ url_for('general.captcha') }}" style="cursor: pointer;border: 1px dashed #ddd;"  title="点击刷新" onclick="refresh_captcha(this)"/>
                    {{ error(form.errors['captcha']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-5">
                    <input class="btn btn-orange" type="submit" value="&nbsp;&nbsp;注册&nbsp;&nbsp;">

                    <p>>已经拥有账号?<a href="{{ url_for('general.login') }}">直接登录</a></p>
                </div>
            </div>

        </form>
    </div>
</div>

<script>
    function refresh_captcha(self){
    $(self).attr('src', '/captcha?' + new Date().getTime())
} 
</script>
{% endblock content %}

daixieadmin/templates/general/wait_for_activate.html
{% extends 'layout.html' %}

{% block title %}
auth
{% endblock title %}

{% block content %}

<p>已发送验证邮件到您的邮箱：{{ email }},请登录到您的邮箱进行验证。</p> <br>
<p>若未收到邮件，请重新发送验证邮件。</p>
<a href="{{ url_for('general.send_activate_email', id=id, email=email) }}">点击重新发送</a>

{% endblock content %}