daixieadmin/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, url_for, redirect, render_template, request,send_from_directory,make_response

from flask_wtf import Form

from werkzeug.utils import secure_filename

from wtforms import TextField, FloatField, SelectField, DateTimeField, TextAreaField, DateTimeField,IntegerField
from wtforms.validators import DataRequired,  Length, Regexp, Email, NumberRange, Optional
from flask_wtf.file import FileField, FileAllowed, FileRequired

from flask.ext.login import login_required, current_user

from daixieadmin.biz.order import OrderBiz
from daixieadmin.biz.user import UserBiz
from daixieadmin.biz.admin import AdminBiz

from daixieadmin.utils.error import DaixieError, fail, success
from daixieadmin.utils.tools import save_file_with_order_id
from daixieadmin.utils.form import User_Exist
from daixieadmin.models.admin import Admin
from daixieadmin.models.order import Order
from daixieadmin import app
from daixieadmin.views import j_login_required

mod = Blueprint('order', __name__)

@mod.route('/create_order', methods=['GET', 'POST'])
@login_required
def create_order():
    '''
    创建订单
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    form = OrderForm()
    if not form.validate_on_submit():
        return render_template('order/create.html', form=form, nav_order_manage='active')

    
    file = request.files['supp_info'] 
    if file :   
        if not allowed_file(file.filename):
            fail("file type error")
            return render_template('order/create.html', form=form, nav_order_manage='active')

    user = UserBiz.get_user_by_email(form.user_email.data)

    cs = AdminBiz.get_admin_by_email(form.cs_email.data)
    solverid = 0
    if form.solver_email.data:
        solver = AdminBiz.get_solver_by_email(form.solver_email.data)
        solverid = solver.id


    order = Order(user.id, cs.id, solverid, form.require_time.data, form.expect_time.data, 
        form.title.data, form.expect_hour.data, form.expect_order_price.data, form.grade.data, 0, \
        form.description.data, form.extra_item.data, form.extra_money.data, form.log.data)

    
    try:
        ret = OrderBiz.create_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')   

    if file :
        order_id = order.id
        save_file_with_order_id(order_id, file)
        order.supp_info = secure_filename(file.filename)
    
    try:
        OrderBiz.edit_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')

    success(ret)
    return redirect(url_for('.my_list'))

@mod.route('/download/<int:id>', methods=['POST', 'GET'])
@j_login_required
def download_file(id):
    order = OrderBiz.get_order_by_id(id).first()
    filename = order.supp_info
    path = app.config['DIR_RESOURCES'] +'/'+ str(id) +'/'
    print "file to be downloaded is at : ", path
    return send_from_directory(path, filename, as_attachment=True)

def allowed_file(filename):
    return True
    #return '.' in filename and \
     #      filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@mod.route('/my_list')
@login_required
def my_list(page=1):
    '''
    查看我的所有订单
    '''
    
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS or current_user.type == Admin.ADMIN_TYPE.ADMIN:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page=1)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page=1)
    return render_template('order/list.html',searchform = searchform, my_list =pager, type=1, nav_order_manage='active')

@mod.route('/search_order',methods=['POST'])
@login_required
def search_order():
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    searchform = SearchForm()
    print "order : ",searchform.order_id.data, "solver :", searchform.solver_id.data
    result = OrderBiz.search_order_by_pager(1,searchform.order_id.data,searchform.solver_id.data,searchform.require_time.data)
    return render_template('order/list.html', searchform = searchform, order_list=result, type=type, nav_order_manage='active')

@mod.route('/order_list')
@login_required
def order_list(page=1):
    '''
    查看所有订单
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()

    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/list.html', searchform = searchform, order_list=pager, type=0, nav_order_manage='active')

@mod.route('/due_order')
@mod.route('/due_order/<int:page>')
@login_required
def due_order(page=0):
    '''
    
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    if page == 0:
        pager = None
        pager = OrderBiz.get_due_order_by_pager(1)
        return render_template('order/list.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')
    else :
        pager = None
        pager = OrderBiz.get_due_order_by_pager(page)
        return render_template('order/morelist.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')

@mod.route('/order_list/<int:page>')
@login_required
def order_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/morelist.html', order_list=pager, paginate=True, nav_order_manage='active')

@mod.route('/my_list/<int:page>')
@login_required
def my_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page)
    return render_template('order/morelist.html', my_list =pager, paginate=True, nav_order_manage='active', tpye=1)    


@mod.route('/more_info/<int:id>')
@login_required
def more_info(id):
    if not current_user.is_authenticated():
        fail(u'权限不足')
        return redirect(url_for('general.index'))
  
    order = OrderBiz.get_order_by_id(id).first()
    if current_user.type == Admin.ADMIN_TYPE.CS:
		return render_template('order/more_info_for_cs.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        return render_template('order/more_info_for_admin.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        return render_template('order/more_info_for_solver.html', order=order, nav_order_manage='active')

@mod.route('/edit_order/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if(current_user.type == Admin.ADMIN_TYPE.SOLVER):
        fail(u'用户权限不足')
        return redirect(url_for('general.index'))    
    if(current_user.type == Admin.ADMIN_TYPE.CS):
        return redirect(url_for('.edit_order_for_cs', id=id))
    else:
        return redirect(url_for('.edit_order_for_admin', id=id))


@mod.route('/edit_order_for_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_cs(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if current_user.type != Admin.ADMIN_TYPE.CS:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = CSEditOrderForm(obj=order)
    form.log.data = ''
    if not form.validate_on_submit():
        print "show order editing"
        return render_template('order/edit_order_for_cs.html', form=form, id=   id, order=order, nav_order_manage='active')
    
    file = request.files['supp_info']    
    if order.status>='1' and order.status <= form.status.data:
        order.status = form.status.data
    order.expect_time = form.expect_time.data
    order.title = form.title.data
    order.description = form.description.data
    order.log = order.log+form.log.data
    order.grade = form.grade.data
    order.expect_hour = form.expect_hour.data
    order.actual_hour = form.actual_hour.data

    if order.status == '3' and form.actual_order_price.data != 0 and form.actual_order_price is not None:
        order.actual_order_price = form.actual_order_price.data

    if file:
        save_file_with_order_id(id, file)
        print file.name
        order.supp_info = secure_filename(file.filename)

    #修改订单
    try:
        ret = OrderBiz.edit_order(order)
        success(ret)
    except DaixieError as e:
        fail(e)
        return render_template('order/edit_order_for_cs.html', form=form, id=id, order=order, nav_order_manage='active')

    return redirect(url_for('admin.home'))

@mod.route('/edit_order_for_admin/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_admin(id):
    if not current_user.is_authenticated() :
        return redirect(url_for('general.index'))    
    if current_user.type != Admin.ADMIN_TYPE.ADMIN:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = AdminEditOrderForm(obj=order)
    if not form.validate_on_submit():
        return render_template('order/edit_order_for_admin.html', form=form, id=id, order=order, nav_order_manage='active')
    

daixieadmin/views/user.py
# -*- coding: utf-8 -*-

from flask import Blueprint, url_for, redirect, render_template, request, abort

from flask_wtf import Form
from wtforms import TextField, PasswordField, SelectField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Regexp
from flask_wtf.file import FileField, FileAllowed, FileRequired

from flask.ext.sqlalchemy import Pagination
from flask.ext.login import login_required, current_user

from daixieadmin.biz.user import UserBiz
from daixieadmin.biz.admin import AdminBiz
from daixieadmin.models.user import User
from daixieadmin.models.admin import Admin
from daixieadmin.utils.error import DaixieError, fail, success, j_ok, j_err
from daixieadmin.utils.http import get_arg

mod = Blueprint('user', __name__)

@mod.route('/home')
@login_required
def home():
	'''
	主页
	'''
	return render_template('user/home.html')

@mod.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
	'''
	个人信息
	'''
	form = ProfileForm(obj=current_user)
	if not form.validate_on_submit():
		return render_template('user/setting.html', form=form)
	user = current_user
	form.populate_obj(user)
	#修改个人信息
	try:
		ret = UserBiz.edit_user_profile(user)
		success(ret)
	except DaixieError as e:
		fail(e)
	return redirect(url_for('.profile'))

@mod.route('/users', methods=['GET'])
@login_required
def j_search_user():
	email = request.args.get('email', '')
	query = request.args.get('query', '')
	page = get_arg('page', 1)
	type = request.args.get('type', '')
	#print "query is ",query

	if(type == 'user'):
		type = User.USER_TYPE.USER

	try:
		if email:
			user = UserBiz.get_user_by_email(email, type)
			users_pager = Pagination(None, 1, 1, 1, [user])
		else:
			users_pager = UserBiz.get_by_like(query, type, page, per_page=10)
	except DaixieError as e:
		return j_err(e)

	users = [{
	'id': user.email,
	'text': user.email,
	'account': user.account
	} for user in users_pager.items if user]

	return j_ok(u'搜索成功', items=users, pages=users_pager.pages)

@mod.route('/solvers', methods=['GET'])
@login_required
def j_search_solvers():
	email = request.args.get('email', '')
	query = request.args.get('query', '')
	page = get_arg('page', 1)
	type = request.args.get('type', '')

	type = Admin.ADMIN_TYPE.SOLVER

	try:
		if email:
			user = AdminBiz.get_cs_by_email(email, type)
			users_pager = Pagination(None, 1, 1, 1, [user])
		else:
			users_pager = AdminBiz.get_by_like(query, type, page, per_page=10)
	except DaixieError as e:
		return j_err(e)

	users = [{
	'id': user.email,
	'text': user.email
	} for user in users_pager.items if user]

	return j_ok(u'搜索成功', items=users, pages=users_pager.pages)
class ProfileForm(Form):
	sex_choices = [('0', u'男'), ('1', u'女')]
	email = TextField(u'登录邮箱', validators=[DataRequired(), Email()])
	nickname = TextField(u'昵称',[Regexp('[\s|\S]')])
	sex = SelectField(u'性别', choices=sex_choices, default='0')
	description = TextAreaField(u'自我介绍',[Regexp('[\s|\S]')])

daixieadmin/templates/import/more_info_for_admin.html
{% from 'import/tools.html' import order_status %}



{% macro more_info_for_admin(order) %}
  <form class="form-horizontal ">
        <table class="table table-bordered">
          <tr>
            <td  colspan="4">
              <div class="control-group">
              <label class="control-label ">订单号</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.id }}</span>
              </div>
              </div>
            </td>

            <td  colspan="4">
              <div class="control-group">
              <label class="control-label ">用户</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.user_id }}</span>
              </div>
              </div>
            </td>

            <td  colspan="4">
              <div class="control-group">
              <label class="control-label ">客服</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.cs_id }}</span>
              </div>
              </div>
            </td>


            <td  colspan="4">
              <div class="control-group">
              <label class="control-label ">解题员</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.solver_id }}</span>
              </div>
              </div>
            </td>
          </tr>
              <div class="control-group">
              <label class="control-label ">标题</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.title }}</span>
              </div>
              </div>

              <div class="control-group">
              <label class="control-label ">创建时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.create_time }}</span>
              </div>
              </div>
              
              <div class="control-group">
              <label class="control-label">要求时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.require_time }}</span>
              </div>
              </div>

              <div class="control-group">
              <label class="control-label">预计完成时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.expect_time }}</span>
              </div>
              </div>
              
              
              <div class="control-group">
              <label class="control-label">订单状态</label>
              <div class="controls">
                {{order_status(order)}}
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">描述信息</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.description if order.description else '无' }}
                  </span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">辅助信息</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                  <a href="{{url_for('order.download_file',id=order.id)}}">{{order.supp_info if order.supp_info else '无'}}</a>
                  </span>
              </div>
              </div>
              

              <div class="control-group">
                <label class="control-label ">日志</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.log }}</span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">订单级别</label>
                  <div class="controls">
                    {% if order.grade == 0 %}
                    <span class="input-xlarge uneditable-input">产品A</span>
                    {% elif order.grade == 1 %}
                    <span class="input-xlarge uneditable-input">产品B</span>
                    {% elif order.grade == 2 %}
                    <span class="input-xlarge uneditable-input">产品C</span>
                    {% elif order.grade == 3 %}
                    <span class="input-xlarge uneditable-input">产品D</span>
                    {% elif order.grade == 4 %}
                    <span class="input-xlarge uneditable-input">产品E</span>
                    {% endif %}
                  </div>
              </div>

              <div class="control-group">
                <label class="control-label ">预计耗时</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.expect_hour }}</span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">实际耗时</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.actual_hour if order.actual_hour else '无'}}
                  </span>
              </div>
              </div>
              

              <div class="control-group">
                <label class="control-label">其他事项</label>
                <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.extra_item if order.extra_item else '无' }}
                  </span>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label">预计订单价格</label>
                <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.expect_order_price }}
                  </span>
                </div>
              </div>

              <div class="control-group">
                <label class="control-label">实际订单价格</label>
                <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.actual_order_price if order.actual_order_price else '无' }}
                  </span>
                </div>
              </div>
    </table>  
   </form>   
{% endmacro%}

daixieadmin/templates/import/more_info_form_for_solver.html
{% from 'import/tools.html' import order_status %}


{% macro more_info_form_for_solver(order) %}
  <form class="form-horizontal ">
              <div class="control-group">
              <label class="control-label ">订单号</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.id }}</span>
              </div>
              </div>

              <div class="control-group">
              <label class="control-label ">标题</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.title }}</span>
              </div>
              </div>

              <div class="control-group">
              <label class="control-label ">创建时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.create_time }}</span>
              </div>
              </div>
              
              <div class="control-group">
              <label class="control-label">要求时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.require_time }}</span>
              </div>
              </div>

              <div class="control-group">
              <label class="control-label">预计完成时间</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.expect_time }}</span>
              </div>
              </div>
              
              
              <div class="control-group">
              <label class="control-label">订单状态</label>
              <div class="controls">
                {{order_status(order)}}
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">描述信息</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.description if order.description else '无' }}
                  </span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">辅助信息</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    <a href="{{url_for('order.download_file',id=order.id)}}">{{order.supp_info if order.supp_info else '无'}}</a>
                  </span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">日志</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.log }}</span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">预计耗时</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">{{ order.expect_hour }}</span>
              </div>
              </div>

              <div class="control-group">
                <label class="control-label ">实际耗时</label>
              <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.actual_hour if order.actual_hour else '无'}}
                  </span>
              </div>
              </div>
              

              <div class="control-group">
                <label class="control-label">其他事项</label>
                <div class="controls">
                  <span class="input-xlarge uneditable-input">
                    {{ order.extra_item if order.extra_item else '无' }}
                  </span>
                </div>
              </div>
              
   </form>   
{% endmacro%}

daixieadmin/templates/import/tools.html
{% macro flashed_msg() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
        <div class="alert alert-dismissable {{ 'alert-'+category }} " >
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>    
    {% endfor %}
{% endwith %}

{% endmacro %}

{% macro error(msg, class='text-danger') %}
    {% if msg %} 
    <span class="{{ class }}">
        {{ msg[0] }}
    </span> 
    {% endif %}
{% endmacro %}


{% macro nav(item, current_user) %}
<ul class="nav">
    <li class="{{ 'active' if item=='user' }}">
    <a href="{{ url_for('user.home') }}">主页</a> 
    </li>
</ul>
{% endmacro %}

{% macro order_status(order) %}
    {% if order.status == 0 %}
       未付款
       {% elif order.status == 1%}
       已付款
       {% elif order.status == 2%}
       解答中
       {% elif order.status == 3 %}
       已解决
    {% endif %}
{% endmacro %}

{% macro captcha(form) %}
<img class="captcha input-small" style="cursor: pointer;border: 1px dashed #ddd;"  title="点击刷新" onclick="refresh_captcha(this)"/>
{{ form.captcha(id="input-captcha", class="input-small", required='required', placeholder='输入验证码') }}
{{ error(form.errors['captcha']) }}
{% endmacro %}


{% macro current_price(customers) %}
{{ '%0.2f' % (130/customers + 5)|float if customers > 1 else 130|float}}
{% endmacro %}


{% macro date(time_range) %}
{% if time_range == 0 %}
2013/11/25
{% elif time_range == 1 %}
2013/12/02
{% elif time_range == 2 %}
2013/12/09
{% elif time_range == 3 %}
2013/12/16
{% elif time_range == 4 %}
2013/12/23
{% elif time_range == 5 %}
2013/12/30
{% elif time_range == 6 %}
2014/01/06
{% elif time_range == 7 %}
2014/01/13
{% elif time_range == 8 %}
2014/01/20
{% elif time_range == 9 %}
2014/01/27
{% else %}
{% endif %}
{% endmacro %}

{% macro list(order_list, type=0) %}
<table id="order_list_table" class="table table-striped table-bordered">
  <tr>
      <th>解题员id</th>
      <th>订单号</th>
      <th>标题</th>
      <th>目前状态</th>
      <th>要求时间</th>
      <th>操作</th>
  </tr>
  {% for order in order_list.items %}
  <tr>
      <td>{{order.solver_id}}</td>
      <td>{{order.id}}</td>
      <td>{{order.title}}</td>
      <td>
         {{ order_status(order) }}
      </td>
      <td>{{order.require_time}}</td>
      <td>
          <a class="btn btn-info" href="{{ url_for('order.more_info', id=order.id) }}">详细</a>
          <a class="btn btn-primary" href="{{ url_for('order.edit_order', id=order.id) }}">修改</a>
      </td>
  </tr>
  {% endfor %}
  </table>

  <div class="aligncenter">
  {% if order_list.has_prev %}<button id="o-pre" class="btn">上一页</button>{% else %}上一页{% endif %} | 
  {% if order_list.has_next %}<button id="o-next" class="btn">下一页</button>{% else %}下一页{% endif %}
  </div>
  
  {% if type == 0%}     
  <a id="oprepage" href="{{ url_for('order.order_list_page', page = order_list.prev_num) }}"></a>
  <a id="onextpage" href="{{ url_for('order.order_list_page', page = order_list.next_num) }}"></a>
  {% endif %}
  
  {% if type == 1%}     
  <a id="oprepage" href="{{ url_for('order.my_list_page', page = order_list.prev_num) }}"></a>
  <a id="onextpage" href="{{ url_for('order.my_list_page', page = order_list.next_num) }}"></a>
  {% endif %}

  {% if type == 2%}     
  <a id="oprepage" href="{{ url_for('order.due_order', page = order_list.prev_num) }}"></a>
  <a id="onextpage" href="{{ url_for('order.due_order', page = order_list.next_num) }}"></a>
  {% endif %}
    
{% endmacro %}