daixieadmin/views/admin.py
# -*- coding: utf-8 -*-


from flask import Blueprint,  url_for, redirect, render_template, request
from flask_wtf import Form
from wtforms import TextField, PasswordField, SelectField
from wtforms.validators import Email, Regexp, DataRequired, EqualTo
                            
from flask.ext.login import login_required, current_user
from flask.ext.sqlalchemy import Pagination

from daixieadmin.utils.error import DaixieError, fail, success, j_ok, j_err
from daixieadmin.utils.http import get_arg

from daixieadmin.models.admin import Admin
from daixieadmin.models.user import User

from daixieadmin.biz.admin import AdminBiz
from daixieadmin.biz.user import UserBiz


mod = Blueprint('admin', __name__)

@mod.route('/home')
@login_required
def home():
	'''
	主页
	'''
	return render_template('admin/home.html', nav_home='active')

@mod.route('/cs_list', methods=['GET', 'POST'])
@login_required
def cs_list():
    '''
    
    '''
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        all_cs = AdminBiz.get_all_CS();
        all_user = UserBiz.get_all_user();
        return render_template('admin/cs_list.html', cs_list=all_cs, user_list=all_user, nav_user_manage='active')
    else:
        return redirect(url_for('general.index'))

@mod.route('/add_cs', methods=['GET', 'POST'])
@login_required
def add_cs():
    '''
    创建解题员和客服
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        form = RegisterForm()
        if not form.validate_on_submit():
            print form.errors
            return render_template('admin/add_cs.html', form=form, nav_user_manage='active')
        try:
            if form.user_type.data=='0':
                cs = Admin(form.email.data, form.passwd.data, form.qq.data)
                ret = AdminBiz.add_CS(cs)
            else:
                solver = Admin(form.email.data, form.passwd.data, form.qq.data)
                ret = AdminBiz.add_solver(solver)
            success(ret)
        except DaixieError as e:
            fail(e)
            return render_template('admin/add_cs.html', form=form, nav_user_manage='active')
        return render_template('admin/add_cs.html', form=form, nav_user_manage='active')     
    else:
        return redirect(url_for('general.index'))

@mod.route('/update_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def update_cs(id):
    '''
    update cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    cs=AdminBiz.get_admin_by_id(id);
    form = AccountForm();
    if not form.validate_on_submit():
        return render_template('admin/update.html', form=form, id=id, type="CS", nav_user_manage='active')
    try:
        cs.passwd = form.passwd.data
        ret = AdminBiz.cs_commit_update(cs=cs)
    except DaixieError as e:
        fail(e)
        return redirect(url_for('.cs_list'))     
    success(ret)
    return redirect(url_for('.cs_list')) 

@mod.route('/update_solver/<int:id>', methods=['GET', 'POST'])
@login_required
def update_solver(id):
    '''
    update solver
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    solver=UserBiz.get_user_by_id(id);
    form = AccountForm();
    if not form.validate_on_submit():
        return render_template('admin/update.html', form=form, id=id, type="SOLVER", nav_user_manage='active')
    try:
        solver.passwd = form.passwd.data
        ret = UserBiz.solver_commit_update(solver=solver)
    except DaixieError as e:
        fail(e)
        return redirect(url_for('.cs_list'))     
    success(ret)
    return redirect(url_for('.cs_list')) 

@mod.route('/delete_cs', methods=['GET', 'POST'])
@mod.route('/delete_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_cs(id):
    '''
    delete cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    cs = AdminBiz.get_admin_by_id(id)
    try:
        ret = AdminBiz.delete_CS(cs=cs)
    except DaixieError as e:
        fail(e) 
    success(ret)
    return redirect(url_for('.cs_list'))

@mod.route('/delete_solver', methods=['GET', 'POST'])
@mod.route('/delete_solver/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_solver(id):
    '''
    delete cs
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    solver = UserBiz.get_user_by_id(id)
    try:
        ret = UserBiz.delete_solver(solver)
        success(ret)
    except DaixieError as e:
        fail(e) 
    
    return redirect(url_for('.cs_list'))

@mod.route('/cs', methods=['GET'])
@login_required
def j_search_cs():
    email = request.args.get('email', '')
    query = request.args.get('query', '')
    page = get_arg('page', 1)

    try:
        if email:
            cs = AdminBiz.get_cs_by_email(email)
            cs_pager = Pagination(None, 1, 1, 1, [cs])
        else:
            cs_pager = AdminBiz.get_by_like(query, 0,page, per_page=10)
    except DaixieError as e:
        return j_err(e)

    cs = [{
    'id': cs.email,
    'text': cs.email
    } for cs in cs_pager.items if cs]

    return j_ok(u'搜索成功', items=cs, pages=cs_pager.pages)

class RegisterForm(Form):
    user_type_choices = [('0', u'客服'), ('1', u'解题员')]

    user_type=SelectField(u'用户类型', choices=user_type_choices, default='0')
    email = TextField(u'邮箱地址*', validators=[DataRequired(), Email(message=u'请填写正确的邮箱地址')])
    passwd = PasswordField(u'密码*', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    passwd_confirm = PasswordField(u'确认密码*', validators=[DataRequired(), EqualTo('passwd', message=u'密码不一致')])
    qq = TextField(u'QQ号*', validators=[DataRequired()])

class AccountForm(Form):
    passwd = PasswordField(u'新密码*', validators=[DataRequired(),Regexp('[\w\d-]{6,20}', message=u'密码必须为6-20位')])
    passwd_confirm = PasswordField(u'确认密码*', validators=[DataRequired(), EqualTo('passwd', message=u'密码不一致')])

daixieadmin/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, url_for, redirect, render_template, request,send_from_directory,make_response

from flask_wtf import Form

from werkzeug.utils import secure_filename

from wtforms import TextField, FloatField, SelectField, DateTimeField, TextAreaField, DateTimeField,IntegerField
from wtforms.validators import DataRequired,  Length, Regexp, Email, NumberRange, Optional
from flask_wtf.file import FileField, FileAllowed, FileRequired

from flask.ext.login import login_required, current_user

from daixieadmin.biz.order import OrderBiz
from daixieadmin.biz.user import UserBiz
from daixieadmin.biz.admin import AdminBiz

from daixieadmin.utils.error import DaixieError, fail, success
from daixieadmin.utils.tools import save_file_with_order_id
from daixieadmin.utils.form import User_Exist
from daixieadmin.models.admin import Admin
from daixieadmin.models.order import Order
from daixieadmin import app
from daixieadmin.views import j_login_required

mod = Blueprint('order', __name__)

@mod.route('/create_order', methods=['GET', 'POST'])
@login_required
def create_order():
    '''
    创建订单
    '''
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    form = OrderForm()
    if not form.validate_on_submit():
        return render_template('order/create.html', form=form, nav_order_manage='active')

    
    file = request.files['supp_info'] 
    if file :   
        if not allowed_file(file.filename):
            fail("file type error")
            return render_template('order/create.html', form=form, nav_order_manage='active')

    user = UserBiz.get_user_by_email(form.user_email.data)

    cs = AdminBiz.get_admin_by_email(form.cs_email.data)
    solverid = 0
    if form.solver_email.data:
        solver = AdminBiz.get_solver_by_email(form.solver_email.data)
        solverid = solver.id


    order = Order(user.id, cs.id, solverid, form.require_time.data, form.expect_time.data, 
        form.title.data, form.expect_hour.data, form.expect_order_price.data, form.grade.data, 0, \
        form.description.data, form.extra_item.data, form.extra_money.data, form.log.data)

    
    try:
        ret = OrderBiz.create_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')   

    if file :
        order_id = order.id
        save_file_with_order_id(order_id, file)
        order.supp_info = secure_filename(file.filename)
    
    try:
        OrderBiz.edit_order(order)
    except DaixieError as e:
        fail(e)
        return render_template('order/create.html', form=form, nav_order_manage='active')

    success(ret)
    return redirect(url_for('.my_list'))

@mod.route('/download/<int:id>', methods=['POST', 'GET'])
@j_login_required
def download_file(id):
    order = OrderBiz.get_order_by_id(id).first()
    filename = order.supp_info
    path = app.config['DIR_RESOURCES'] +'/'+ str(id) +'/'
    print "file to be downloaded is at : ", path
    return send_from_directory(path, filename, as_attachment=True)

def allowed_file(filename):
    return True
    #return '.' in filename and \
     #      filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@mod.route('/my_list')
@login_required
def my_list(page=1):
    '''
    查看我的所有订单
    '''
    
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS or current_user.type == Admin.ADMIN_TYPE.ADMIN:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page=1)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page=1)
    return render_template('order/list.html',searchform = searchform, my_list =pager, type=1, nav_order_manage='active')

@mod.route('/search_order',methods=['POST'])
@login_required
def search_order():
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    searchform = SearchForm()
    print "order : ",searchform.order_id.data, "solver :", searchform.solver_id.data
    result = OrderBiz.search_order_by_pager(1,searchform.order_id.data,searchform.solver_id.data,searchform.require_time.data)
    return render_template('order/list.html', searchform = searchform, order_list=result, type=type, nav_order_manage='active')

@mod.route('/order_list')
@login_required
def order_list(page=1):
    '''
    查看所有订单
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()

    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/list.html', searchform = searchform, order_list=pager, type=0, nav_order_manage='active')

@mod.route('/due_order')
@mod.route('/due_order/<int:page>')
@login_required
def due_order(page=0):
    '''
    
    '''

    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))    
    searchform = SearchForm()
    if page == 0:
        pager = None
        pager = OrderBiz.get_due_order_by_pager(1)
        return render_template('order/list.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')
    else :
        pager = None
        pager = OrderBiz.get_due_order_by_pager(page)
        return render_template('order/morelist.html', searchform = searchform, order_list=pager, type=2, nav_order_manage='active')

@mod.route('/order_list/<int:page>')
@login_required
def order_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    pager = OrderBiz.get_order_list_by_pager(page)
    return render_template('order/morelist.html', order_list=pager, paginate=True, nav_order_manage='active')

@mod.route('/my_list/<int:page>')
@login_required
def my_list_page(page=1):
    '''
    查看所有订单
    '''
    if not current_user.is_authenticated():
        raise u'权限不足'    
    pager = None
    if current_user.type == Admin.ADMIN_TYPE.CS:
        pager = OrderBiz.get_order_list_by_admin_id(current_user.id, page)
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        pager = OrderBiz.get_order_list_by_solver_id(current_user.id, page)
    return render_template('order/morelist.html', my_list =pager, paginate=True, nav_order_manage='active', tpye=1)    


@mod.route('/more_info/<int:id>')
@login_required
def more_info(id):
    if not current_user.is_authenticated():
        fail(u'权限不足')
        return redirect(url_for('general.index'))
  
    order = OrderBiz.get_order_by_id(id).first()
    if current_user.type == Admin.ADMIN_TYPE.CS:
		return render_template('order/more_info_for_cs.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.ADMIN:
        return render_template('order/more_info_for_admin.html', order=order, nav_order_manage='active')
    if current_user.type == Admin.ADMIN_TYPE.SOLVER:
        return render_template('order/more_info_for_solver.html', order=order, nav_order_manage='active')

@mod.route('/edit_order/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if(current_user.type == Admin.ADMIN_TYPE.SOLVER):
        fail(u'用户权限不足')
        return redirect(url_for('general.index'))    
    if(current_user.type == Admin.ADMIN_TYPE.CS):
        return redirect(url_for('.edit_order_for_cs', id=id))
    else:
        return redirect(url_for('.edit_order_for_admin', id=id))


@mod.route('/edit_order_for_cs/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_cs(id):
    if not current_user.is_authenticated():
        return redirect(url_for('general.index'))
    if current_user.type != Admin.ADMIN_TYPE.CS:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = CSEditOrderForm(obj=order)
    form.log.data = ''
    if not form.validate_on_submit():
        print "show order editing"
        return render_template('order/edit_order_for_cs.html', form=form, id=   id, order=order, nav_order_manage='active')
    
    file = request.files['supp_info']    
    if order.status>='1' and order.status <= form.status.data:
        order.status = form.status.data
    order.expect_time = form.expect_time.data
    order.title = form.title.data
    order.description = form.description.data
    order.log = order.log+form.log.data
    order.grade = form.grade.data
    order.expect_hour = form.expect_hour.data
    order.actual_hour = form.actual_hour.data

    if order.status == '3' and form.actual_order_price.data != 0 and form.actual_order_price is not None:
        order.actual_order_price = form.actual_order_price.data

    if file:
        save_file_with_order_id(id, file)
        print file.name
        order.supp_info = secure_filename(file.filename)

    #修改订单
    try:
        ret = OrderBiz.edit_order(order)
        success(ret)
    except DaixieError as e:
        fail(e)
        return render_template('order/edit_order_for_cs.html', form=form, id=id, order=order, nav_order_manage='active')

    return redirect(url_for('admin.home'))

@mod.route('/edit_order_for_admin/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_order_for_admin(id):
    if not current_user.is_authenticated() :
        return redirect(url_for('general.index'))    
    if current_user.type != Admin.ADMIN_TYPE.ADMIN:
        fail(u"用户权限不足")
        return redirect(url_for('general.index'))

    order = OrderBiz.get_order_by_id(id).first()
    form = AdminEditOrderForm(obj=order)
    if not form.validate_on_submit():
        return render_template('order/edit_order_for_admin.html', form=form, id=id, order=order, nav_order_manage='active')
    

daixieadmin/templates/413.html
{% extends "layout.html" %}

{% block content %}
<div class="col-md-12">
<h1 class="text-center">不要这样, 发送文件过大!</h1>
</div>
{% endblock %}

daixieadmin/templates/error.html
{% extends "layout.html" %}
{% block main %}
    <h1>Oh!</h1>
    <div class="alert alert-error">
        {{ message }}
    </div>
{% endblock %}

daixieadmin/templates/layout.html
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="给大学生提供代写作业的平台">
    <meta name="keywords" content="大学 作业 美国">
    <meta charset="utf-8"  http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>TA帮后台管理</title>
    {% assets "favicon" %}
    <link rel="icon" 
      type="image/png" 
      href="{{ ASSET_URL }}" />
    {% endassets %}
    {% assets "all_css" %}
      <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
    {% endassets %}
    <style type="text/css">
      .aligncenter{text-align:center;}
    </style>
    <!--[if lt IE 9]>
      <script src="ie/js/html5shiv.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"  href="{{ url_for('general.index') }}">{{ config['SITE_NAME'] }}</a>
        </div>
        <div class="navbar-collapse collapse">
          {% if current_user.is_authenticated() %}
          <ul class="nav nav-user navbar-nav">
            <li class="{{ nav_home }}"><a href="{{ url_for('admin.home') }}">首页</a></li>
            <li class="dropdown {{ nav_order_manage }}">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  订单管理<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                {% if current_user.type ==0 or current_user.type ==1 %}
                  <li><a href="{{ url_for('order.create_order') }}">创建订单</a></li>
                   <li><a href="{{ url_for('order.order_list') }}">查看所有订单</a></li>
                {% endif %}
                   <li><a href="{{ url_for('order.my_list') }}">查看我的订单</a></li>
              </ul>
            </li>
            {% if current_user.type==1 %}
            <li class="dropdown {{ nav_user_manage}}">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    用户管理<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('admin.cs_list') }}">查看所有用户</a></li>
                    <li><a href="{{ url_for('admin.add_cs') }}">创建用户</a></li>
                </ul>
            </li>
            {% endif %}
          </ul>
          {% endif %}
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated()%}
              <li><a href="{{ url_for('admin.home') }}">{{ current_user.nickname if current_user.nickname else current_user.email }}</a></li>
              <li><a href="{{ url_for('general.logout') }}">注销</a></li>
            {% else %}
              {% block loginform %}
              <li class="{{ nav_login }}"><a href="{{ url_for('general.login') }}">登录</a></li>
              {% endblock loginform %}
            {% endif %}
          </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </div>

    {% block ad %}
    {% endblock ad %}

    {% from 'import/tools.html' import flashed_msg %}
    <div class="container">
        <div class="row">
            {{ flashed_msg() }}
        </div>
    </div>

    {% block wrapper %}
    <div class="container wrapper">
          {% block search %}
    {% endblock %}
        <div id="main" class="row">
    {% block content %}
    {% endblock content %}
        </div>
    </div>
    {% endblock wrapper %}

    <hr>
    <footer>
      <p>&copy; 2014 daixie.com・all rights reserved・京ICP备12026711号·文化部监督电子邮箱:wlwh@vip.sina.com</p>
    </footer>

    {% assets "all_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block js %}
    {# <script> 对特定网页导入工具性js时使用 </script> #}
    {% endblock js %}
  </body>
</html>

daixieadmin/templates/layout_o.html
<!DOCTYPE html>
<html>
    <head>
        <title>代写</title>

        <meta name="description" content="给大学生提供代写作业的平台">
        <meta name="keywords" content="大学 作业 美国">
        <meta charset="utf-8"  http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        {% assets "all_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
        {% endassets %}

        <!--[if lt IE 9]>
        <script src="ie/js/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body>
        <header class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('general.index') }}">{{ config['SITE_NAME'] }}<span class="TM">BETA</span></a>
                </div>
                <nav class="collapse navbar-collapse" role="navigation">
                    {% if current_user.is_authenticated() %}
                    <ul class="nav nav-user navbar-nav navbar-left">
                        <li><a href="{{ url_for('admin.home') }}">首页</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                订单管理<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('order.create_order') }}">创建订单</a></li>
                                 <li><a href="{{ url_for('order.my_list') }}">查看我的订单</a></li>
                                 <li><a href="{{ url_for('order.order_list') }}">查看所有订单</a></li>
                            </ul>
                        </li>
                        {% if current_user.type==1 %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                用户管理<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('admin.cs_list') }}">查看所有用户</a></li>
                                <li><a href="{{ url_for('admin.add_cs') }}">创建用户</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                账户管理<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">关联账户设置</a></li>
                            </ul>
                        </li>
                    </ul>
                    {% endif %}
                    <ul class="nav navbar-nav navbar-right">
                        {% if not current_user.is_authenticated() %}
                        <li><a href="{{ url_for('general.login') }}">登录</a></li>
                        {% else %}
                        <li><a href="{{ url_for('admin.home') }}">{{ current_user.nickname if current_user.nickname else current_user.email }}</a></li>
                        <li><a href="{{ url_for('general.logout') }}">注销</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </header>

        {% block ad %}
        {% endblock ad %}

        {% from 'import/tools.html' import flashed_msg %}
        <div class="container">
            <div class="row">
                {{ flashed_msg() }}
            </div>
        </div>
        
        {% block wrapper %}
        <div class="container wrapper">
            <div class="row">
        {% block content %}{% endblock content %}
            </div>
        </div>
        {% endblock wrapper %}
        
        <hr>
        <div id="footer">
            <div class="container">
                <p class="navbar-text">© 2013 example.com・all rights reserved・京ICP备12026711号·文化部监督电子邮箱:wlwh@vip.sina.com</p>
            </div>
        </div>

        {% assets "all_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block js %}
        {# <script> 对特定网页导入工具性js时使用 </script> #}
        {% endblock js %}
    </body>
</html>